pluginManagement {
    repositories {
        mavenCentral()
        google()
        jcenter()
        mavenLocal()
        maven(url = "https://dl.bintray.com/kotlin/ktor")
        gradlePluginPortal()
        maven(url = "https://jitpack.io")

    }
}
//include(":talaiot")
include(":talaiot:base")
include(":talaiot:talaiot-request")
include(":docs")
//include(":publishers:push-gateway-publisher")
//include(":publishers:rethinkdb-publisher")
//include(":publishers:elastic-search-publisher")
//include(":publishers:graph-publisher")
//include(":publishers:influxdb-publisher")
include(":publishers:base-publisher")
//include(":publishers:hybrid-publisher")
//include(":plugins:influxdb-plugin")
include(":plugins:base-plugin")
//include(":plugins:elastic-search-plugin")
//include(":plugins:graph-plugin")
//include(":plugins:hybrid-plugin")
//include(":plugins:rethinkdb-plugin")
//include(":plugins:push-gateway-plugin")
//include(":plugins:talaiot-plugin")
